In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [2]:
data=pd.read_csv('insurance.csv')
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
real_x=data.iloc[:,0:6].values
real_y=data.iloc[:,6].values


In [4]:
le=LabelEncoder()
real_x[:,1]=le.fit_transform(real_x[:,1])
real_x[:,1]

array([0, 1, 1, ..., 0, 0, 0], dtype=object)

In [5]:
real_x[:,4]=le.fit_transform(real_x[:,4])
real_x[:,4]

array([1, 0, 0, ..., 0, 0, 1], dtype=object)

In [6]:
real_x[:,5]=le.fit_transform(real_x[:,5])
real_x[:,5]
real_x

array([[19, 0, 27.9, 0, 1, 3],
       [18, 1, 33.77, 1, 0, 2],
       [28, 1, 33.0, 3, 0, 2],
       ...,
       [18, 0, 36.85, 0, 0, 2],
       [21, 0, 25.8, 0, 0, 3],
       [61, 0, 29.07, 0, 1, 1]], dtype=object)

In [7]:
ct=ColumnTransformer([("region",OneHotEncoder(),[5])],remainder='passthrough')
real_x=ct.fit_transform(real_x)


In [8]:
real_x=real_x[:,1:]

In [9]:
real_x[:,5]

array([27.9, 33.77, 33.0, ..., 36.85, 25.8, 29.07], dtype=object)

In [10]:
real_x

array([[0.0, 0.0, 1.0, ..., 27.9, 0, 1],
       [0.0, 1.0, 0.0, ..., 33.77, 1, 0],
       [0.0, 1.0, 0.0, ..., 33.0, 3, 0],
       ...,
       [0.0, 1.0, 0.0, ..., 36.85, 0, 0],
       [0.0, 0.0, 1.0, ..., 25.8, 0, 0],
       [1.0, 0.0, 0.0, ..., 29.07, 0, 1]], dtype=object)

In [11]:
training_x,test_x,training_y,test_y=train_test_split(real_x,real_y,test_size=0.3,random_state=0)

In [12]:
MLR=LinearRegression()
MLR.fit(training_x,training_y)
pred_y=MLR.predict(test_x)


In [13]:
MLR.coef_

array([ -561.90114536,  -994.74867954,  -799.44893726,   256.43544682,
         -47.54675517,   335.36907276,   472.70978916, 23435.99116948])

In [14]:
test_y[1]

8547.6913

In [15]:
pred_y[1]

9544.907094215598

In [16]:
print(MLR.score(training_x,training_y)*100)
print(MLR.score(test_x,test_y)*100)

73.09569871174702
79.09160991789905


In [17]:
pred_y[0]

11253.193645802015

In [18]:
test_y[0]

9724.53

In [19]:
import statsmodels.formula.api as sm

In [20]:
real_x=np.append(arr=np.ones((1338,1)).astype(int),values=real_x,axis=1)
real_x=np.array(real_x,dtype=float)

In [21]:
x_opt=real_x[:,[0,1,2,3,4,5,6,7,8]] 
reg_OLS=sm.OLS(endog = real_y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     500.8
Date:                Mon, 16 Mar 2020   Prob (F-statistic):               0.00
Time:                        16:41:38   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1329   BIC:                         2.716e+04
Df Model:                           8                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.194e+04    987.819    -12.086      0.000   -1.39e+04      -1e+04
x1          -352.9639    476.276     -0.741      0.459   -1287.298     581.370
x2         -1035.0220    478.692     -2.162      0.031   -1974.097     -95.947
x3          -960.0510    477.933     -2.009      0.045   -1897.636     -22.466
x4           256.8564     11.899     21.587      0.000     233.514     280.199
x5          -131.3144    332.945     -0.394      0.693    -784.470     521.842
x6           339.1935     28.599     11.860      0.000     283.088     395.298
x7           475.5005    137.804      3.451      0.001     205.163     745.838
x8          2.385e+04    413.153     57.723      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      300.366   Durbin-Watson:                   2.088
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              718.887
Skew:                           1.211   Prob(JB):                    7.86e-157
Kurtosis:                       5.651   Cond. No.                         311.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
x_opt=real_x[:,[0,1,2,3,4,6,7,8]] 
reg_OLS=sm.OLS(endog = real_y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.750
Method:                 Least Squares   F-statistic:                     572.7
Date:                Mon, 16 Mar 2020   Prob (F-statistic):               0.00
Time:                        16:41:38   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1330   BIC:                         2.715e+04
Df Model:                           7                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.199e+04    978.762    -12.250      0.000   -1.39e+04   -1.01e+04
x1          -352.1821    476.120     -0.740      0.460   -1286.211     581.847
x2         -1034.3601    478.537     -2.162      0.031   -1973.130     -95.590
x3          -959.3747    477.778     -2.008      0.045   -1896.656     -22.094
x4           256.9736     11.891     21.610      0.000     233.646     280.301
x5           338.6646     28.559     11.858      0.000     282.639     394.690
x6           474.5665    137.740      3.445      0.001     204.355     744.778
x7          2.384e+04    411.856     57.875      0.000     2.3e+04    2.46e+04
==============================================================================
Omnibus:                      300.735   Durbin-Watson:                   2.089
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              720.516
Skew:                           1.212   Prob(JB):                    3.48e-157
Kurtosis:                       5.654   Cond. No.                         309.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
x_opt=real_x[:,[0,2,3,4,6,7,8]] 
reg_OLS=sm.OLS(endog = real_y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.751
Model:                            OLS   Adj. R-squared:                  0.750
Method:                 Least Squares   F-statistic:                     668.3
Date:                Mon, 16 Mar 2020   Prob (F-statistic):               0.00
Time:                        16:41:38   Log-Likelihood:                -13548.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1331   BIC:                         2.715e+04
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.217e+04    949.538    -12.812      0.000    -1.4e+04   -1.03e+04
x1          -858.4696    415.206     -2.068      0.039   -1672.998     -43.941
x2          -782.7452    413.756     -1.892      0.059   -1594.430      28.940
x3           257.0064     11.889     21.617      0.000     233.683     280.330
x4           338.6413     28.554     11.860      0.000     282.625     394.657
x5           471.5441    137.656      3.426      0.001     201.498     741.590
x6          2.384e+04    411.659     57.921      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      300.125   Durbin-Watson:                   2.092
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              716.587
Skew:                           1.211   Prob(JB):                    2.48e-156
Kurtosis:                       5.643   Cond. No.                         295.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
x_opt=real_x[:,[0,2,4,6,7,8]] 
reg_OLS=sm.OLS(endog = real_y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.750
Model:                            OLS   Adj. R-squared:                  0.749
Method:                 Least Squares   F-statistic:                     799.7
Date:                Mon, 16 Mar 2020   Prob (F-statistic):               0.00
Time:                        16:41:38   Log-Likelihood:                -13550.
No. Observations:                1338   AIC:                         2.711e+04
Df Residuals:                    1332   BIC:                         2.714e+04
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -1.228e+04    948.666    -12.940      0.000   -1.41e+04   -1.04e+04
x1          -578.8620    388.384     -1.490      0.136   -1340.774     183.050
x2           257.1365     11.901     21.607      0.000     233.791     280.482
x3           333.4448     28.449     11.721      0.000     277.635     389.255
x4           468.0668    137.777      3.397      0.001     197.783     738.350
x5          2.385e+04    412.023     57.895      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      302.906   Durbin-Watson:                   2.089
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              726.891
Skew:                           1.220   Prob(JB):                    1.44e-158
Kurtosis:                       5.662   Cond. No.                         294.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [49]:
x_opt=real_x[:,[0,4,5,7,8]] 
reg_OLS=sm.OLS(endog = real_y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.724
Model:                            OLS   Adj. R-squared:                  0.723
Method:                 Least Squares   F-statistic:                     873.1
Date:                Mon, 16 Mar 2020   Prob (F-statistic):               0.00
Time:                        16:43:11   Log-Likelihood:                -13617.
No. Observations:                1338   AIC:                         2.724e+04
Df Residuals:                    1333   BIC:                         2.727e+04
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -2882.9935    571.997     -5.040      0.000   -4005.106   -1760.881
x1           273.1318     12.426     21.981      0.000     248.756     297.508
x2            61.3224    349.688      0.175      0.861    -624.677     747.322
x3           486.2092    144.774      3.358      0.001     202.199     770.219
x4          2.384e+04    433.236     55.021      0.000     2.3e+04    2.47e+04
==============================================================================
Omnibus:                      266.138   Durbin-Watson:                   2.089
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              649.185
Skew:                           1.071   Prob(JB):                    1.07e-141
Kurtosis:                       5.657   Cond. No.                         142.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [50]:
MLR=LinearRegression()
MLR.fit(training_x[:,[0,4,5,7]],training_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [51]:
y_pred = MLR.predict(test_x[:, [0,4,5,7]])

In [52]:
y_pred[0]

8192.78137825482

In [53]:
test_y[0]

9724.53

In [54]:
pred_y[0]

11253.193645802015

In [55]:
test_y[1]   #test_y prediction

8547.6913

In [56]:
pred_y[1]   #Before Backward Elimination

9544.907094215598

In [57]:
y_pred[1]  #After Backward Elimination        ##MORE Efficient

8002.587670380915

In [58]:
test_y[5]

4500.33925

In [59]:
pred_y[5]

4004.4626840527

In [60]:
y_pred[5]

4719.562460978248