In [18]:
import numpy as np
mylist=[1,2,3,4]
arr=np.array(mylist)
type(np.array(mylist))
arr

array([1, 2, 3, 4])

In [15]:
from numpy import *
arr=array([2,3,4,5])
print(arr)
print(type(arr.dtype))

[2 3 4 5]
<class 'numpy.dtype'>


In [17]:
list=[4,5,6,7]
arr=array(list)
arr
print(type(arr.dtype))

<class 'numpy.dtype'>


In [73]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
 np.zeros(5,int)

array([0, 0, 0, 0, 0])

In [28]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [31]:
np.ones((5,5),int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [42]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [52]:
np.random.randint(0,100,10)

array([49, 30, 50,  7, 30, 67,  5, 92, 12, 73])

In [55]:
np.random.randint(0,100,(4,4))

array([[13, 32, 51, 38],
       [41, 30, 85, 71],
       [21,  0, 93, 90],
       [15, 61, 14, 25]])

In [61]:
np.random.seed(101)
np.random.randint(0,100,10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [72]:
np.random.seed(101)
arr1=np.random.randint(0,100,10)
arr1.max()
arr1.min()
arr1.mean()
arr1.argmax()
arr1.argmin()
arr1.reshape(2,5)

array([[95, 11, 81, 70, 63],
       [87, 75,  9, 77, 40]])

In [87]:
mat=arange(0,100).reshape(10,10)
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [77]:
mat[0,:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
mat[2,:]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [91]:
mat[:,2]

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [88]:
mat[2,2]

22

In [89]:
mat[1,8]

18

In [92]:
mat[0:3,0:3]

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [93]:
mat[2:3,0:3]

array([[20, 21, 22]])