In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data=pd.read_csv('Uber.csv')
data.head()

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0            15     1800000           5800                      50   
1            15     1790000           6200                      50   
2            15     1780000           6400                      60   
3            25     1778000           6500                      60   
4            25     1750000           6550                      60   

   Numberofweeklyriders  
0                192000  
1                190400  
2                191200  
3                177600  
4                176800

In [3]:
real_x=data.iloc[:,0:4].values
real_y=data.iloc[:,4].values

In [4]:
training_x,test_x,training_y,test_y=train_test_split(real_x,real_y,test_size=0.33,random_state=0)

In [5]:
MLR=LinearRegression()
MLR.fit(training_x,training_y)
pred_y=MLR.predict(test_x)

In [6]:
pred_y

array([188629.50339543, 136559.39301861, 167923.33044203, 126048.35876704,
       178953.09696641, 166223.49873765, 130975.62779069, 167971.3136973 ,
       141866.03727522])

In [7]:
test_y

array([191200, 126080, 160800, 115696, 178400, 163200, 123888, 161600,
       150400], dtype=int64)

In [8]:
print(MLR.coef_)

[-5.68775893e+02  1.30158909e-01 -5.49376209e-02  1.22759763e+02]


In [9]:
print(MLR.intercept_)

-41535.70104644974


In [10]:
pred_y[0]

188629.50339543127

In [11]:
test_y[0]

191200

In [12]:
#y0=b0+b1x1+b2x2+b3x3+y4x4+.........bnxn
y0=MLR.intercept_+MLR.coef_[0]*test_x[0][0]+MLR.coef_[1]*test_x[0][1]+MLR.coef_[2]*test_x[0][2]+MLR.coef_[3]*test_x[0][3]
y0

188629.50339543127

In [13]:
print(MLR.score(training_x,training_y)*100)
print(MLR.score(test_x,test_y)*100)

94.28364724316815
91.57379222488224


In [18]:
X1=[[60,500000,60000,150]]
out=MLR.predict(X1)
print(out)

[4534.9069841]
