In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [2]:
data=pd.read_csv("Admission_Predict.csv")
data.head()

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR   CGPA  \
0           1        337          118                  4  4.5   4.5  9.65   
1           2        324          107                  4  4.0   4.5  8.87   
2           3        316          104                  3  3.0   3.5  8.00   
3           4        322          110                  3  3.5   2.5  8.67   
4           5        314          103                  2  2.0   3.0  8.21   

   Research  Chance of Admit   
0         1              0.92  
1         1              0.76  
2         1              0.72  
3         1              0.80  
4         0              0.65

In [3]:
real_x=data.iloc[:,1:-1].values
real_y=data.iloc[:,-1].values

In [4]:
real_x=real_x[:,1:]

In [5]:
train_x,test_x,train_y,test_y=train_test_split(real_x,real_y,test_size=.3,random_state=0)

In [6]:
reg=LinearRegression()
reg.fit(train_x,train_y)
pred_y=reg.predict(test_x)

In [7]:
pred_y

array([0.63821107, 0.84051503, 0.78333292, 0.8768249 , 0.62182092,
       0.63836598, 0.54795852, 0.72299485, 0.54248932, 0.72819902,
       0.59474727, 0.69897172, 0.61270818, 0.76868751, 0.87105333,
       0.52058184, 0.81817876, 0.63155957, 0.75070428, 0.55044023,
       0.52805992, 0.70382349, 0.53382051, 0.91720935, 0.83527877,
       0.72567404, 0.68796167, 0.48379856, 0.57947846, 0.59890424,
       0.7221788 , 0.4860832 , 0.68302594, 0.83858747, 0.54465007,
       0.61036102, 0.83170529, 0.87149923, 0.60799774, 0.6640759 ,
       0.66486748, 0.89912827, 0.86352849, 0.72259357, 0.76229874,
       0.79498489, 0.97525745, 0.85434336, 0.64885446, 0.64682486,
       0.64191499, 0.62627035, 0.61970325, 0.79759914, 0.70584563,
       0.84742134, 0.54670545, 0.8693917 , 0.61345488, 0.64421927,
       0.5044085 , 0.90495174, 0.62462657, 0.96308528, 0.71759099,
       0.62678599, 0.71119355, 0.84556138, 0.52696382, 0.7617988 ,
       0.89477562, 0.77771299, 0.70576119, 0.62301486, 0.79269

In [8]:
test_y

array([0.64, 0.85, 0.8 , 0.91, 0.68, 0.54, 0.54, 0.65, 0.52, 0.79, 0.65,
       0.74, 0.64, 0.79, 0.89, 0.43, 0.81, 0.73, 0.8 , 0.58, 0.57, 0.74,
       0.6 , 0.93, 0.88, 0.67, 0.7 , 0.57, 0.48, 0.64, 0.69, 0.47, 0.57,
       0.87, 0.39, 0.53, 0.84, 0.89, 0.63, 0.7 , 0.72, 0.86, 0.91, 0.75,
       0.74, 0.76, 0.96, 0.81, 0.6 , 0.62, 0.69, 0.68, 0.59, 0.8 , 0.71,
       0.78, 0.69, 0.89, 0.67, 0.58, 0.44, 0.89, 0.53, 0.92, 0.66, 0.73,
       0.52, 0.86, 0.54, 0.72, 0.92, 0.55, 0.75, 0.73, 0.85, 0.91, 0.75,
       0.71, 0.54, 0.68, 0.62, 0.88, 0.59, 0.74, 0.8 , 0.63, 0.77, 0.65,
       0.57, 0.7 , 0.76, 0.78, 0.71, 0.73, 0.73, 0.95, 0.64, 0.53, 0.48,
       0.64, 0.91, 0.72, 0.96, 0.67, 0.75, 0.59, 0.72, 0.85, 0.71, 0.77,
       0.49, 0.68, 0.71, 0.5 , 0.57, 0.86, 0.38, 0.94, 0.79, 0.93, 0.74,
       0.78, 0.89, 0.86, 0.49, 0.59, 0.42, 0.61, 0.71, 0.56, 0.7 , 0.82,
       0.86, 0.64, 0.64, 0.67, 0.69, 0.37, 0.73, 0.84, 0.77, 0.78, 0.74,
       0.76, 0.76, 0.65, 0.79, 0.73, 0.81, 0.9 ])

In [9]:
print(reg.score(train_x,train_y)*100)
print(reg.score(test_x,test_y)*100)

82.55523254133644
78.91797160799005


In [11]:
pred_y[0]

0.638211069247045

In [12]:
test_y[0]

0.64

In [13]:
import statsmodels.formula.api as sm
import statsmodels.regression.linear_model as Im

In [16]:
real_x=np.append(arr=np.ones((500,1)).astype(int),values=real_x,axis=1)

In [17]:
real_x=np.array(real_x,dtype=float)

In [25]:
x_opt=real_x[:,[0,1,2,3,4,5,6]]  
reg_OLS=sm.OLS(endog = real_y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.817
Model:                            OLS   Adj. R-squared:                  0.815
Method:                 Least Squares   F-statistic:                     366.7
Date:                Sat, 21 Mar 2020   Prob (F-statistic):          3.46e-178
Time:                        19:19:12   Log-Likelihood:                 694.52
No. Observations:                 500   AIC:                            -1375.
Df Residuals:                     493   BIC:                            -1346.
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -0.9699      0.064    -15.055      0.000      -1.097      -0.843
x1             0.0043      0.001      5.431      0.000       0.003       0.006
x2             0.0066      0.004      1.724      0.085      -0.001       0.014
x3             0.0010      0.005      0.225      0.822      -0.008       0.010
x4             0.0160      0.004      3.830      0.000       0.008       0.024
x5             0.1326      0.009     14.694      0.000       0.115       0.150
x6             0.0313      0.006      4.881      0.000       0.019       0.044
==============================================================================
Omnibus:                      101.334   Durbin-Watson:                   0.809
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              208.218
Skew:                          -1.099   Prob(JB):                     6.11e-46
Kurtosis:                       5.273   Cond. No.                     2.56e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.56e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [27]:
x_opt=real_x[:,[0,1,4,5,6]]  
reg_OLS=sm.OLS(endog = real_y, exog=x_opt).fit()
reg_OLS.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.816
Model:                            OLS   Adj. R-squared:                  0.814
Method:                 Least Squares   F-statistic:                     547.1
Date:                Sat, 21 Mar 2020   Prob (F-statistic):          4.23e-180
Time:                        19:20:22   Log-Likelihood:                 692.59
No. Observations:                 500   AIC:                            -1375.
Df Residuals:                     495   BIC:                            -1354.
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         -1.0271      0.056    -18.260      0.000      -1.138      -0.917
x1             0.0045      0.001      5.882      0.000       0.003       0.006
x2             0.0185      0.004      4.818      0.000       0.011       0.026
x3             0.1376      0.009     16.068      0.000       0.121       0.154
x4             0.0323      0.006      5.052      0.000       0.020       0.045
==============================================================================
Omnibus:                       97.546   Durbin-Watson:                   0.812
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              196.633
Skew:                          -1.068   Prob(JB):                     2.00e-43
Kurtosis:                       5.208   Cond. No.                     2.23e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.23e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [31]:
reg=LinearRegression()
reg.fit(train_x[:,[0,1,4,5]],train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [33]:
y_pred = reg.predict(test_x[:, [0,1,4,5]])

In [35]:
y_pred

array([0.61832749, 0.82192413, 0.79459575, 0.86413217, 0.64500821,
       0.65341488, 0.56094694, 0.7028472 , 0.55135636, 0.71993734,
       0.61176368, 0.71799911, 0.62109482, 0.77278769, 0.86662725,
       0.54551499, 0.79919617, 0.61924892, 0.75255329, 0.55644037,
       0.52195641, 0.68399874, 0.52280762, 0.90848048, 0.84324859,
       0.71434376, 0.71548818, 0.47836546, 0.57766946, 0.5880174 ,
       0.69898202, 0.46726016, 0.69404928, 0.82550927, 0.54579655,
       0.587521  , 0.83559776, 0.86581248, 0.62227721, 0.65978946,
       0.64539643, 0.88870755, 0.874776  , 0.71171686, 0.77196012,
       0.78579782, 0.97953163, 0.84994117, 0.62581121, 0.63846652,
       0.6428075 , 0.61620004, 0.60880713, 0.79590843, 0.71491074,
       0.83966497, 0.56094694, 0.86285593, 0.63153661, 0.64851857,
       0.51844605, 0.90690835, 0.61231901, 0.959571  , 0.72180536,
       0.63597144, 0.70081512, 0.85648135, 0.54108016, 0.74472407,
       0.91337679, 0.78441187, 0.71365813, 0.62542299, 0.80169

In [43]:
test_y[10]

0.65

In [44]:
pred_y[10]

0.5947472744998362

In [45]:
y_pred[10]

0.6117636825555937